---
servers:
  - tcp://localhost:1883
client_id: gombus2mqtt
topic_prefix: mbus
homeassistant_autodiscover:
  enabled: true
  prefix: homeassistant
device: /dev/ttyUSB0
interval_sec: 5
read_timeout_ms: 500
meters:
  - name: meter1
    address: 0
    template: zri_heat
meter_templates:
  zri_heat:
    - publish: false
    - name:
      unit: Wh
      device_class: energy
      publish: false
    - name:
      unit: date
      device_class:
      publish: false
    - name:
      unit: date
      device_class:
      publish: false
    - name:
      unit: Wh
      device_class: energy
      publish: false
    - name:
      unit: Wh
      device_class: energy
      publish: false
    - name:
      unit: date
      device_class:
      publish: false
    - name:
      unit: Wh
      device_class: energy
      publish: false
    - name: Volumen
      unit: m³
      device_class: volume
      publish: true
    - name: Vorlauftemperatur
      unit: °C
      device_class: temperature
      publish: true
    - name: Ruecklauftemperatur
      unit: °C
      device_class: temperature
      publish: true
    - name: Temperaturdifferenz
      unit: K
      device_class: temperature
      publish: true
    - name: Leistung
      unit: W
      device_class: power
      publish: true
    - name: Durchfluss
      unit: m³/h
      device_class: volume_flow_rate
      publish: true
    - publish: false
    - publish: false
    - publish: false
    - publish: false
